import { describe, expect, it, vi, beforeEach } from "vitest";
import request from "supertest";
import { randomUUID } from "node:crypto";
import { createApp } from "../src/app.js";
import { briefAi } from "../src/modules/briefs/brief.ai.js";
import { buildClinicalBriefPdf } from "../src/modules/briefs/brief.pdf.js";
import { prisma } from "../src/lib/prisma.js";

const { state, nextId } = vi.hoisted(() => {
  return {
    state: {
      users: [] as Array<{
        id: string;
        email: string;
        passwordHash: string;
        role: "MEMBER" | "ADMIN";
        emailVerifiedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
      }>,
      symptomLogs: [] as Array<{
        id: string;
        userId: string;
        category: string;
        severity: string;
        occurredAt: Date;
        notes: string | null;
      }>,
      cycleEntries: [] as Array<{
        id: string;
        userId: string;
        date: Date;
        flow: string | null;
        isPeriodStart: boolean;
        isPeriodEnd: boolean;
        notes: string | null;
      }>,
      treatments: [] as Array<{
        id: string;
        userId: string;
        name: string;
        category: string;
        startDate: Date;
        endDate: Date | null;
        notes: string | null;
      }>,
      briefs: [] as Array<{
        id: string;
        userId: string;
        fromDate: Date;
        toDate: Date;
        symptomSummary: unknown;
        cycleSummary: unknown;
        treatmentSummary: unknown;
        frequencyComparison: unknown;
        coOccurrence: unknown;
        treatmentImpact: unknown;
        persistentSymptoms: unknown;
        interpretation: unknown;
        aiNarrative: string;
        aiDiscussionTopics: unknown;
        createdAt: Date;
      }>,
    },
    nextId: () => randomUUID(),
  };
});

const now = () => new Date();

const { aiState } = vi.hoisted(() => ({
  aiState: {
    nextResponse: null as null | {
      narrative: string;
      discussionTopics: string[];
      patterns?: unknown[];
    },
    shouldThrow: false,
  },
}));

vi.mock("../src/modules/briefs/brief.ai.js", () => ({
  briefAi: {
    generate: vi.fn(async () => {
      if (aiState.shouldThrow) throw new Error("simulated AI failure");
      if (!aiState.nextResponse) {
        throw new Error("test didn't configure an AI response");
      }
      // Most tests in this file predate Stage 4 and don't care about
      // patterns at all — default to an empty array (a real, valid
      // response shape per brief.ai.ts's own system prompt) rather
      // than requiring every one of this file's aiState.nextResponse
      // assignments to specify it explicitly. Spread after the
      // default so a test that does set patterns overrides it.
      return { patterns: [], ...aiState.nextResponse };
    }),
  },
}));

vi.mock("../src/modules/briefs/brief.pdf.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../src/modules/briefs/brief.pdf.js")>();
  return {
    ...actual,
    // Wraps (not replaces) the real implementation — PDF bytes are
    // still genuinely generated by pdfkit, matching every existing
    // PDF test in this file. This only adds the ability to inspect
    // exactly what `brief` argument buildClinicalBriefPdf was called
    // with, which is the only reliable way to prove the PDF route
    // used the persisted treatmentSummary: pdfkit's standard fonts
    // compress their content streams by default, so grepping the raw
    // PDF bytes for treatment text is not a dependable check the way
    // it would be for an uncompressed format.
    buildClinicalBriefPdf: vi.fn(actual.buildClinicalBriefPdf),
  };
});

vi.mock("../src/lib/redis.js", () => ({
  redis: { ping: vi.fn().mockResolvedValue("PONG"), quit: vi.fn() },
}));

vi.mock("../src/modules/auth/mailer.js", () => ({
  sendVerificationEmail: vi.fn().mockResolvedValue(undefined),
  sendPasswordResetEmail: vi.fn().mockResolvedValue(undefined),
  sendOrganizationInviteEmail: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("../src/lib/prisma.js", () => ({
  prisma: {
    user: {
      findUnique: vi.fn(({ where }: { where: { email?: string; id?: string } }) => {
        const found = state.users.find((u) => u.email === where.email || u.id === where.id);
        return Promise.resolve(found ?? null);
      }),
      create: vi.fn(({ data }: { data: { email: string; passwordHash: string } }) => {
        const user = {
          id: nextId(),
          email: data.email,
          passwordHash: data.passwordHash,
          role: "MEMBER" as const,
          emailVerifiedAt: null,
          createdAt: now(),
          updatedAt: now(),
        };
        state.users.push(user);
        return Promise.resolve(user);
      }),
      update: vi.fn(({ where, data }: { where: { id: string }; data: Record<string, unknown> }) => {
        const user = state.users.find((u) => u.id === where.id)!;
        Object.assign(user, data);
        return Promise.resolve(user);
      }),
    },
    session: {
      create: vi.fn(({ data }: { data: Record<string, unknown> }) =>
        Promise.resolve({
          id: nextId(),
          revokedAt: null,
          replacedBySessionId: null,
          createdAt: now(),
          ...data,
        }),
      ),
      findUnique: vi.fn().mockResolvedValue(null),
      update: vi.fn(),
      updateMany: vi.fn().mockResolvedValue({ count: 0 }),
      findMany: vi.fn().mockResolvedValue([]),
    },
    emailVerificationToken: {
      updateMany: vi.fn().mockResolvedValue({ count: 0 }),
      create: vi.fn().mockResolvedValue({ id: nextId() }),
      findFirst: vi.fn().mockResolvedValue(null),
      update: vi.fn().mockResolvedValue({}),
    },
    passwordResetToken: {
      updateMany: vi.fn().mockResolvedValue({ count: 0 }),
      create: vi.fn().mockResolvedValue({ id: nextId() }),
      findFirst: vi.fn().mockResolvedValue(null),
      update: vi.fn().mockResolvedValue({}),
    },
    auditLog: {
      create: vi.fn().mockResolvedValue({}),
    },
    onboardingProfile: {
      findUnique: vi.fn().mockResolvedValue(null),
    },
    symptomLog: {
      findMany: vi.fn(
        ({ where }: { where: { userId: string; occurredAt?: { gte?: Date; lte?: Date } } }) => {
          const results = state.symptomLogs.filter((log) => {
            if (log.userId !== where.userId) return false;
            if (where.occurredAt?.gte && log.occurredAt < where.occurredAt.gte) return false;
            if (where.occurredAt?.lte && log.occurredAt > where.occurredAt.lte) return false;
            return true;
          });
          return Promise.resolve(results);
        },
      ),
      // Matches treatmentRepository.countSymptomLogsInWindows exactly:
      // occurredAt: { gte, lt } — an exclusive upper bound, unlike
      // findMany's gte/lte above. Two separate calls (one per window)
      // rather than a single query with both windows, matching that
      // function's own Promise.all shape.
      count: vi.fn(
        ({ where }: { where: { userId: string; occurredAt: { gte: Date; lt: Date } } }) => {
          const count = state.symptomLogs.filter((log) => {
            if (log.userId !== where.userId) return false;
            if (log.occurredAt < where.occurredAt.gte) return false;
            if (log.occurredAt >= where.occurredAt.lt) return false;
            return true;
          }).length;
          return Promise.resolve(count);
        },
      ),
    },
    cycleEntry: {
      findMany: vi.fn(
        ({ where }: { where: { userId: string; date?: { gte?: Date; lte?: Date } } }) => {
          const results = state.cycleEntries.filter((entry) => {
            if (entry.userId !== where.userId) return false;
            if (where.date?.gte && entry.date < where.date.gte) return false;
            if (where.date?.lte && entry.date > where.date.lte) return false;
            return true;
          });
          return Promise.resolve(results);
        },
      ),
    },
    treatment: {
      // Matches treatment.repository.ts's listOverlappingRange exactly:
      // where: { userId, startDate: { lte: toDate }, OR: [{ endDate: null }, { endDate: { gte: fromDate } }] }
      findMany: vi.fn(
        ({
          where,
        }: {
          where: {
            userId: string;
            startDate: { lte: Date };
            OR: [{ endDate: null }, { endDate: { gte: Date } }];
          };
        }) => {
          const toDate = where.startDate.lte;
          const fromDate = where.OR[1].endDate.gte;
          const results = state.treatments
            .filter((t) => t.userId === where.userId)
            .filter((t) => t.startDate <= toDate)
            .filter((t) => t.endDate === null || t.endDate >= fromDate)
            .sort((a, b) => b.startDate.getTime() - a.startDate.getTime());
          return Promise.resolve(results);
        },
      ),
    },
    clinicalBrief: {
      create: vi.fn(({ data }: { data: Record<string, unknown> }) => {
        const brief = { id: nextId(), createdAt: now(), ...data } as (typeof state.briefs)[number];
        state.briefs.push(brief);
        return Promise.resolve(brief);
      }),
      findMany: vi.fn(
        ({ where, skip, take }: { where: { userId: string }; skip: number; take: number }) => {
          const results = state.briefs
            .filter((b) => b.userId === where.userId)
            .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
            .slice(skip, skip + take);
          return Promise.resolve(results);
        },
      ),
      count: vi.fn(({ where }: { where: { userId: string } }) =>
        Promise.resolve(state.briefs.filter((b) => b.userId === where.userId).length),
      ),
      findFirst: vi.fn(({ where }: { where: { id: string; userId: string } }) => {
        const found = state.briefs.find((b) => b.id === where.id && b.userId === where.userId);
        return Promise.resolve(found ?? null);
      }),
      deleteMany: vi.fn(({ where }: { where: { id: string; userId: string } }) => {
        const before = state.briefs.length;
        state.briefs = state.briefs.filter(
          (b) => !(b.id === where.id && b.userId === where.userId),
        );
        return Promise.resolve({ count: before - state.briefs.length });
      }),
    },
  },
}));

const VALID_PASSWORD = "Sup3rSecret!Pass";

async function registerAndLogin(agent: ReturnType<typeof request.agent>, email: string) {
  const register = await agent.post("/auth/register").send({ email, password: VALID_PASSWORD });
  await agent.post("/auth/login").send({ email, password: VALID_PASSWORD });
  return register.body.data.id as string;
}

function addSymptomLog(
  userId: string,
  overrides: Partial<(typeof state.symptomLogs)[number]> = {},
) {
  const log = {
    id: nextId(),
    userId,
    category: "HOT_FLASH",
    severity: "MODERATE",
    occurredAt: now(),
    notes: null,
    ...overrides,
  };
  state.symptomLogs.push(log);
  return log;
}

function addTreatment(userId: string, overrides: Partial<(typeof state.treatments)[number]> = {}) {
  const treatment = {
    id: nextId(),
    userId,
    name: "Estradiol patch",
    category: "HRT",
    startDate: new Date("2026-01-10"),
    endDate: null,
    notes: null,
    ...overrides,
  };
  state.treatments.push(treatment);
  return treatment;
}

beforeEach(() => {
  state.users = [];
  state.symptomLogs = [];
  state.cycleEntries = [];
  state.treatments = [];
  state.briefs = [];
  aiState.nextResponse = null;
  aiState.shouldThrow = false;
});

const RANGE = { fromDate: "2026-01-01", toDate: "2026-02-01" };

describe("POST /briefs", () => {
  it("requires authentication", async () => {
    const app = createApp();
    const res = await request(app).post("/briefs").send(RANGE);
    expect(res.status).toBe(401);
  });

  it("rejects fromDate >= toDate", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "range@embr.health");

    const res = await agent.post("/briefs").send({ fromDate: "2026-02-01", toDate: "2026-01-01" });
    expect(res.status).toBe(400);
  });

  it("computes the structured summary correctly and persists it alongside the AI content", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "brief1@embr.health");

    addSymptomLog(userId, {
      category: "HOT_FLASH",
      severity: "MODERATE",
      occurredAt: new Date("2026-01-05"),
    });
    addSymptomLog(userId, {
      category: "HOT_FLASH",
      severity: "SEVERE",
      occurredAt: new Date("2026-01-10"),
    });
    addSymptomLog(userId, {
      category: "BRAIN_FOG",
      severity: "MILD",
      occurredAt: new Date("2026-01-15"),
    });
    // Outside the requested range — must not be counted.
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-03-01") });

    aiState.nextResponse = {
      narrative: "Hot flashes were logged most frequently, with increasing severity.",
      discussionTopics: ["Ask whether hot flash severity trends are typical at this stage."],
    };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
    expect(res.body.data.symptomSummary).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          category: "HOT_FLASH",
          count: 2,
          severityBreakdown: { MODERATE: 1, SEVERE: 1 },
        }),
        expect.objectContaining({ category: "BRAIN_FOG", count: 1 }),
      ]),
    );
    expect(res.body.data.symptomSummary).toHaveLength(2); // not 3 — the out-of-range log excluded
    expect(res.body.data.aiNarrative).toBe(aiState.nextResponse.narrative);
    expect(res.body.data.aiDiscussionTopics).toEqual(aiState.nextResponse.discussionTopics);
    expect(state.briefs).toHaveLength(1);
  });

  it("computes cycle summary from period-start entries", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "brief2@embr.health");

    state.cycleEntries.push(
      {
        id: nextId(),
        userId,
        date: new Date("2026-01-01"),
        flow: "MEDIUM",
        isPeriodStart: true,
        isPeriodEnd: false,
        notes: null,
      },
      {
        id: nextId(),
        userId,
        date: new Date("2026-01-29"),
        flow: "LIGHT",
        isPeriodStart: true,
        isPeriodEnd: false,
        notes: null,
      },
    );
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
    expect(res.body.data.cycleSummary).toEqual({
      averageCycleLengthDays: 28,
      cycleCount: 1,
      periodDaysLogged: 2,
    });
  });

  it("surfaces an AI failure as an error rather than silently generating a broken brief", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "brief-fail@embr.health");
    aiState.shouldThrow = true;

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBeGreaterThanOrEqual(500);
    expect(state.briefs).toHaveLength(0);
  });
});

// Integration coverage only — the comparison arithmetic itself
// (increase/decrease/zero-denominator/etc.) is already exhaustively
// covered in period-comparison.test.ts. These tests exist to prove
// the brief wires that already-tested function in correctly: the
// right previous-period window gets queried, and the result reaches
// the persisted brief and the read path unchanged.
describe("POST /briefs — frequency comparison (deterministic, no AI involvement)", () => {
  it("compares the requested period against the immediately preceding period of equal length", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "freqcomp1@embr.health");

    // Current period (RANGE: 2026-01-01 to 2026-02-01): 2 HOT_FLASH.
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-05") });
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-20") });
    // Previous period (2025-11-30 to 2025-12-31): 1 HOT_FLASH, 1 FATIGUE.
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2025-12-15") });
    addSymptomLog(userId, { category: "FATIGUE", occurredAt: new Date("2025-12-20") });
    // Outside both periods entirely — must not be counted as either.
    addSymptomLog(userId, { category: "ANXIETY", occurredAt: new Date("2025-01-01") });

    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };
    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
    expect(res.body.data.frequencyComparison).toEqual(
      expect.arrayContaining([
        {
          category: "FATIGUE",
          currentCount: 0,
          previousCount: 1,
          absoluteChange: -1,
          percentageChange: -100,
          direction: "decreased",
        },
        {
          category: "HOT_FLASH",
          currentCount: 2,
          previousCount: 1,
          absoluteChange: 1,
          percentageChange: 100,
          direction: "increased",
        },
      ]),
    );
    expect(res.body.data.frequencyComparison).toHaveLength(2); // not 3 — ANXIETY is in neither period
  });

  it("does not fabricate a percentage change when the previous period has no observations for a category", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "freqcomp2@embr.health");

    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-05") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.frequencyComparison).toEqual([
      {
        category: "HOT_FLASH",
        currentCount: 1,
        previousCount: 0,
        absoluteChange: 1,
        percentageChange: null,
        direction: "increased",
      },
    ]);
  });

  it("returns an empty array, not null, when both periods genuinely have no symptom logs", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "freqcomp3@embr.health");
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.frequencyComparison).toEqual([]);
  });

  it("GET /briefs/:id returns the same frequencyComparison the POST response returned", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "freqcomp4@embr.health");
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-05") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const created = await agent.post("/briefs").send(RANGE);
    const fetched = await agent.get(`/briefs/${created.body.data.id}`);

    expect(fetched.body.data.frequencyComparison).toEqual(created.body.data.frequencyComparison);
  });

  it("a brief generated before this field existed reads back frequencyComparison, coOccurrence, treatmentImpact, persistentSymptoms, and interpretation as null, not an empty array", async () => {
    // Simulates a pre-existing row rather than exercising POST — a
    // real NULL JSONB column comes back from Prisma as JS `null`
    // (never `undefined`), which is what this constructs directly,
    // matching schema.prisma's doc comment: null means "never
    // computed for this brief," a materially different fact from an
    // empty array ("computed, found nothing") for frequencyComparison,
    // treatmentImpact, and persistentSymptoms. coOccurrence shares the
    // same "old snapshot" null case, even though its own null is
    // overloaded for a different reason (see schema.prisma's doc
    // comment on that column) — all five covered in the same test
    // rather than near-duplicate ones, since all five are proving the
    // identical "old row, new column" scenario.
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "freqcomp5@embr.health");

    state.briefs.push({
      id: nextId(),
      userId,
      fromDate: new Date("2026-01-01"),
      toDate: new Date("2026-02-01"),
      symptomSummary: [],
      cycleSummary: { averageCycleLengthDays: null, cycleCount: 0, periodDaysLogged: 0 },
      treatmentSummary: [],
      frequencyComparison: null,
      coOccurrence: null,
      treatmentImpact: null,
      persistentSymptoms: null,
      interpretation: null,
      aiNarrative: "A brief from before this field existed.",
      aiDiscussionTopics: ["n/a"],
      createdAt: now(),
    });

    const res = await agent.get(`/briefs/${state.briefs[0]!.id}`);

    expect(res.body.data.frequencyComparison).toBeNull();
    expect(res.body.data.coOccurrence).toBeNull();
    expect(res.body.data.treatmentImpact).toBeNull();
    expect(res.body.data.persistentSymptoms).toBeNull();
    expect(res.body.data.interpretation).toBeNull();
  });
});

// Integration coverage only — detectSymptomCoOccurrence's own
// detection logic (threshold, tie-breaking, UTC day boundaries, same-
// category exclusion) is already exhaustively covered in
// trends-co-occurrence.test.ts. These tests exist to prove the brief
// wires that already-tested function in correctly: computed over the
// brief's own requested period (not the comparison period), reaching
// the persisted brief and the read path unchanged.
describe("POST /briefs — symptom co-occurrence (deterministic, no AI involvement)", () => {
  it("persists the qualifying pair when co-occurrence meets the existing threshold", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "cooccur1@embr.health");

    // BRAIN_FOG and HOT_FLASH share 3 calendar days — exactly
    // MIN_CO_OCCURRENCE_DAYS, the existing threshold reused as-is.
    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "BRAIN_FOG", occurredAt: new Date(date) });
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
    expect(res.body.data.coOccurrence).toEqual({
      categoryA: "BRAIN_FOG",
      categoryB: "HOT_FLASH",
      days: 3,
    });

    // Same structural proof style as the treatment-persistence test —
    // the PDF is built from the persisted brief, so a non-null
    // coOccurrence must reach it too, not just the null case already
    // covered elsewhere.
    const pdfRes = await agent.get(`/briefs/${res.body.data.id}/pdf`);
    expect(pdfRes.status).toBe(200);
    const pdfCalls = vi.mocked(buildClinicalBriefPdf).mock.calls;
    const lastPdfCallArg = pdfCalls[pdfCalls.length - 1]![0];
    expect(lastPdfCallArg.coOccurrence).toEqual({
      categoryA: "BRAIN_FOG",
      categoryB: "HOT_FLASH",
      days: 3,
    });
  });

  it("represents the absence of a qualifying relationship as null, not an empty object", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "cooccur2@embr.health");

    // Only 2 shared days — one below the threshold.
    addSymptomLog(userId, { category: "BRAIN_FOG", occurredAt: new Date("2026-01-05") });
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-05") });
    addSymptomLog(userId, { category: "BRAIN_FOG", occurredAt: new Date("2026-01-10") });
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-10") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.coOccurrence).toBeNull();
  });

  it("only considers dates inside the requested brief period, not the comparison period or logs outside it", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "cooccur3@embr.health");

    // 3 shared days, but in December — entirely before RANGE
    // (2026-01-01 to 2026-02-01) starts. Even though this range is
    // exactly the comparison period computePreviousPeriod() would
    // compute for RANGE, co-occurrence must never consider it — only
    // frequencyComparison does.
    for (const date of ["2025-12-05", "2025-12-10", "2025-12-15"]) {
      addSymptomLog(userId, { category: "BRAIN_FOG", occurredAt: new Date(date) });
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.coOccurrence).toBeNull();
  });

  it("when multiple pairs qualify, persists the same single strongest pair detectSymptomCoOccurrence would select on its own", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "cooccur4@embr.health");

    // ANXIETY/BRAIN_FOG share 3 days; BRAIN_FOG/HOT_FLASH share 4 —
    // the stronger pair, and the one that must win.
    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "ANXIETY", occurredAt: new Date(date) });
    }
    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15", "2026-01-20"]) {
      addSymptomLog(userId, { category: "BRAIN_FOG", occurredAt: new Date(date) });
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.coOccurrence).toEqual({
      categoryA: "BRAIN_FOG",
      categoryB: "HOT_FLASH",
      days: 4,
    });
  });

  it("GET /briefs/:id returns the same coOccurrence the POST response returned", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "cooccur5@embr.health");
    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "BRAIN_FOG", occurredAt: new Date(date) });
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const created = await agent.post("/briefs").send(RANGE);
    const fetched = await agent.get(`/briefs/${created.body.data.id}`);

    expect(fetched.body.data.coOccurrence).toEqual(created.body.data.coOccurrence);
    expect(fetched.body.data.coOccurrence).not.toBeNull();
  });
});

// Integration coverage only — computeTreatmentImpactWindows'/
// buildTreatmentImpact's own window-math and insufficientData-flag
// logic is already exhaustively covered in treatment-impact.test.ts.
// These tests exist to prove the brief wires those already-tested
// functions in correctly: only for treatments that started inside
// the brief's own requested period, name/category embedded alongside
// the computed windows, reaching the persisted brief and the read
// path unchanged.
describe("POST /briefs — treatment impact (deterministic, no AI involvement)", () => {
  it("computes before/after impact for a treatment that started inside the requested period", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tximpact1@embr.health");

    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: null,
    });
    // 2 logs in the 14 days before 2026-01-10, 3 in the 14 days after.
    addSymptomLog(userId, { occurredAt: new Date("2026-01-02") });
    addSymptomLog(userId, { occurredAt: new Date("2026-01-05") });
    addSymptomLog(userId, { occurredAt: new Date("2026-01-11") });
    addSymptomLog(userId, { occurredAt: new Date("2026-01-15") });
    addSymptomLog(userId, { occurredAt: new Date("2026-01-20") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
    expect(res.body.data.treatmentImpact).toHaveLength(1);
    expect(res.body.data.treatmentImpact[0]).toMatchObject({
      name: "Estradiol patch",
      category: "HRT",
      windowDays: 14,
      before: { logCount: 2, days: 14 },
      after: { logCount: 3, days: 14 },
      insufficientData: false,
    });
  });

  it("excludes a treatment that merely overlaps the period without starting inside it", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tximpact2@embr.health");

    // Started well before RANGE (2026-01-01 to 2026-02-01), still
    // ongoing — appears in treatmentSummary, but its before/after
    // windows would be computed around a start date unrelated to
    // this brief's period, so it must not appear in treatmentImpact.
    addTreatment(userId, {
      name: "Long-running supplement",
      category: "SUPPLEMENT",
      startDate: new Date("2025-06-01"),
      endDate: null,
    });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toHaveLength(1); // still summarized
    expect(res.body.data.treatmentImpact).toEqual([]); // but no impact entry
  });

  it("returns an empty array, not null, when no treatment started inside the period", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "tximpact3@embr.health");
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentImpact).toEqual([]);
  });

  it("flags insufficientData for a treatment whose 'after' window is genuinely short", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tximpact4@embr.health");

    // Ended just 1 day after it started — the "after" window is
    // capped at the treatment's own endDate regardless of how far in
    // the future "today" is, so this is short no matter when the
    // test actually runs, unlike an ongoing treatment near the end of
    // the requested period (whose "after" window is unaffected by the
    // brief's own toDate — see computeTreatmentImpactWindows's doc
    // comment: only the treatment's own endDate/today and windowDays
    // bound it).
    addTreatment(userId, {
      name: "Short trial",
      category: "MEDICATION",
      startDate: new Date("2026-01-10"),
      endDate: new Date("2026-01-11"),
    });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentImpact[0]).toMatchObject({
      after: { days: 1 },
      insufficientData: true,
    });
  });

  it("preserves multiple treatments that each started inside the period independently", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tximpact5@embr.health");

    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-05"),
      endDate: null,
    });
    addTreatment(userId, {
      name: "Magnesium",
      category: "SUPPLEMENT",
      startDate: new Date("2026-01-15"),
      endDate: null,
    });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentImpact).toHaveLength(2);
    expect(res.body.data.treatmentImpact.map((t: { name: string }) => t.name).sort()).toEqual([
      "Estradiol patch",
      "Magnesium",
    ]);
  });

  it("GET /briefs/:id returns the same treatmentImpact the POST response returned", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tximpact6@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: null,
    });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const created = await agent.post("/briefs").send(RANGE);
    const fetched = await agent.get(`/briefs/${created.body.data.id}`);

    expect(fetched.body.data.treatmentImpact).toEqual(created.body.data.treatmentImpact);
    expect(fetched.body.data.treatmentImpact).not.toEqual([]);
  });
});

// Integration coverage only — detectPersistentSymptoms' own filtering
// logic (the floor, the both-periods requirement) is already
// exhaustively covered in persistent-symptoms.test.ts. These tests
// exist to prove the brief wires that already-tested function in
// correctly against its own real frequencyComparison output — no new
// counting happens here, so most of what's worth proving is that the
// two stay in agreement.
describe("POST /briefs — persistent symptoms (deterministic, no AI involvement)", () => {
  it("flags a category present in both periods at or above the floor, derived from frequencyComparison alone", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "persist1@embr.health");

    // Current period (RANGE): 3 HOT_FLASH. Previous period
    // (2025-11-30 to 2025-12-31): 1 HOT_FLASH — present, no floor
    // required there.
    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2025-12-15") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
    expect(res.body.data.persistentSymptoms).toEqual(["HOT_FLASH"]);
  });

  it("does not flag a category below the floor in the current period, even if present in both", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "persist2@embr.health");

    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-05") }); // only 1
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2025-12-15") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.persistentSymptoms).toEqual([]);
  });

  it("does not flag a category newly reported this period only, no matter how frequent", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "persist3@embr.health");

    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    // No HOT_FLASH logs in the previous period at all.
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.persistentSymptoms).toEqual([]);
  });

  it("returns an empty array, not null, when nothing qualifies", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "persist4@embr.health");
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.persistentSymptoms).toEqual([]);
  });

  it("stays in agreement with frequencyComparison for the same generated brief", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "persist5@embr.health");

    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2025-12-15") });
    addSymptomLog(userId, { category: "FATIGUE", occurredAt: new Date("2026-01-20") }); // new, 1x
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const res = await agent.post("/briefs").send(RANGE);

    const hotFlashEntry = res.body.data.frequencyComparison.find(
      (e: { category: string }) => e.category === "HOT_FLASH",
    );
    expect(hotFlashEntry).toMatchObject({ currentCount: 3, previousCount: 1 });
    expect(res.body.data.persistentSymptoms).toEqual(["HOT_FLASH"]);
  });

  it("GET /briefs/:id returns the same persistentSymptoms the POST response returned", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "persist6@embr.health");
    for (const date of ["2026-01-05", "2026-01-10", "2026-01-15"]) {
      addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date(date) });
    }
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2025-12-15") });
    aiState.nextResponse = { narrative: "n/a", discussionTopics: ["n/a"] };

    const created = await agent.post("/briefs").send(RANGE);
    const fetched = await agent.get(`/briefs/${created.body.data.id}`);

    expect(fetched.body.data.persistentSymptoms).toEqual(created.body.data.persistentSymptoms);
    expect(fetched.body.data.persistentSymptoms).not.toEqual([]);
  });
});

describe("POST /briefs — treatment summary (deterministic, no AI involvement)", () => {
  beforeEach(() => {
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"] };
  });

  it("includes a treatment entirely inside the BRIEF period", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-inside@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: new Date("2026-01-20"),
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toEqual([
      { name: "Estradiol patch", category: "HRT", startDate: "2026-01-10", endDate: "2026-01-20" },
    ]);
  });

  it("includes a treatment that started before the period but continues into it", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-overlap-start@embr.health");
    // RANGE is 2026-01-01 to 2026-02-01 — this treatment started well
    // before the range but is still active partway through it.
    addTreatment(userId, {
      name: "Magnesium glycinate",
      category: "SUPPLEMENT",
      startDate: new Date("2025-11-01"),
      endDate: new Date("2026-01-15"),
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toHaveLength(1);
    expect(res.body.data.treatmentSummary[0].startDate).toBe("2025-11-01");
  });

  it("includes an ongoing treatment (endDate null)", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-ongoing@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2025-06-01"),
      endDate: null,
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toEqual([
      { name: "Estradiol patch", category: "HRT", startDate: "2025-06-01", endDate: null },
    ]);
  });

  it("excludes a treatment that ended before the period started", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-ended-before@embr.health");
    addTreatment(userId, {
      name: "Old supplement",
      category: "SUPPLEMENT",
      startDate: new Date("2025-10-01"),
      endDate: new Date("2025-12-15"),
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toEqual([]);
  });

  it("excludes a treatment that starts after the period ends", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-starts-after@embr.health");
    addTreatment(userId, {
      name: "Future treatment",
      category: "MEDICATION",
      startDate: new Date("2026-03-01"),
      endDate: null,
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toEqual([]);
  });

  it("includes multiple overlapping treatments correctly", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-multiple@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2025-06-01"),
      endDate: null,
    });
    addTreatment(userId, {
      name: "Magnesium",
      category: "SUPPLEMENT",
      startDate: new Date("2026-01-05"),
      endDate: new Date("2026-01-25"),
    });
    addTreatment(userId, {
      name: "Not in range",
      category: "OTHER",
      startDate: new Date("2026-06-01"),
      endDate: null,
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toHaveLength(2);
    expect(res.body.data.treatmentSummary.map((t: { name: string }) => t.name).sort()).toEqual([
      "Estradiol patch",
      "Magnesium",
    ]);
  });

  it("never includes notes, even when a treatment has efficacy-adjacent notes text", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-notes@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: null,
      notes: "Seems to be helping a lot, hot flashes much better since starting.",
    });

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.body.data.treatmentSummary).toEqual([
      { name: "Estradiol patch", category: "HRT", startDate: "2026-01-10", endDate: null },
    ]);
    expect(JSON.stringify(res.body)).not.toContain("helping");
    expect(JSON.stringify(res.body)).not.toContain("Seems to be");
  });

  it("CRITICAL: the AI receives interpretation, but never the treatment name, notes, or a raw treatment object", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-ai-boundary@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: null,
      notes: "This should never reach the model under any circumstances.",
    });
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-12") });

    const res = await agent.post("/briefs").send(RANGE);
    expect(res.status).toBe(201);

    // The real object passed to the mocked briefAi.generate() call —
    // not a re-derivation, the actual argument.
    const calls = vi.mocked(briefAi.generate).mock.calls;
    const lastCallArg = calls[calls.length - 1]![0];

    // 1. briefAi.generate() receives interpretation, alongside the
    // same four fields as before — nothing else, still an exact list.
    expect(Object.keys(lastCallArg).sort()).toEqual([
      "cycleSummary",
      "fromDate",
      "interpretation",
      "symptomSummary",
      "toDate",
    ]);
    expect(lastCallArg).not.toHaveProperty("treatmentSummary");
    expect(lastCallArg).not.toHaveProperty("treatments");

    // 5. The interpretation still contains the deterministic Stage 4
    // information the AI needs — this treatment started inside RANGE
    // with a symptom log in its after-window, so it produces a real
    // treatment_window_changed pattern (alongside a frequency_increased
    // pattern for the same symptom log, since it has no counterpart in
    // the previous period — not zero patterns, and not just the one
    // this test is specifically about).
    const treatmentPattern = lastCallArg.interpretation.patterns.find(
      (p: { type: string }) => p.type === "treatment_window_changed",
    );
    expect(treatmentPattern).toBeDefined();

    // 2, 3, 4. The interpretation sent to the AI contains none of the
    // treatment's identifying data — name, notes, or category (which
    // would only be reachable via a raw treatment object, since no
    // Stage4Pattern field carries it).
    const sentJson = JSON.stringify(lastCallArg);
    expect(sentJson).not.toContain("Estradiol");
    expect(sentJson).not.toContain("never reach the model");
    expect(sentJson).not.toContain("HRT");

    // 6. The canonical, server-side Stage4Result (never sent to the
    // AI) can still contain the treatment name — brief.service.ts
    // never exposes that object externally by design, so there's
    // nothing for a black-box integration test to inspect here beyond
    // what's already verified directly in
    // stage4-ai-projection.test.ts's "does not mutate the original
    // canonical Stage4Result" and in stage4-interpretation.test.ts.

    // 7. Provenance validation still operates against the canonical
    // result, not the AI-safe projection — verified end to end by the
    // dedicated "Stage 4 interpretation wiring" tests below, which
    // control exactly what the mocked AI echoes back.
  });
});

describe("POST /briefs — Stage 4 interpretation wiring and provenance validation", () => {
  // A single, predictable pattern with a fully known id — HOT_FLASH
  // logged twice in the current period, never in the previous one, so
  // frequencyComparison produces exactly one "increased" entry and
  // nothing else (no treatment, no co-occurrence pair, no second
  // category) — the deterministic id is exactly
  // "frequency_increased:HOT_FLASH", per stage4-interpretation.ts's
  // own id construction rule, computed here rather than inspected
  // from a prior response.
  function setUpOneKnownPattern(userId: string) {
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-05") });
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-10") });
  }
  const KNOWN_PATTERN = {
    id: "frequency_increased:HOT_FLASH",
    type: "frequency_increased",
    observation:
      "HOT_FLASH was reported on 2 days during the current period, compared with 0 during the previous period.",
    interpretation:
      "This represents an increase in how often HOT_FLASH was reported, relative to the previous period.",
    caveat:
      "This reflects self-reported logging frequency only. It does not indicate severity, cause, or clinical significance.",
    confidence: "descriptive",
    evidenceRef: { category: "HOT_FLASH" },
  };

  it("generates a deterministic Stage 4 pattern from the structured input and sends it to the AI", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire1@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"] };

    await agent.post("/briefs").send(RANGE);

    const lastCallArg = vi.mocked(briefAi.generate).mock.calls.at(-1)![0];
    expect(lastCallArg.interpretation.patterns).toEqual(
      expect.arrayContaining([expect.objectContaining({ id: KNOWN_PATTERN.id })]),
    );
  });

  it("never gives the AI the raw evidence (frequencyComparison, coOccurrence, treatmentImpact) it could use to construct a pattern itself", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire2@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"] };

    await agent.post("/briefs").send(RANGE);

    const lastCallArg = vi.mocked(briefAi.generate).mock.calls.at(-1)![0];
    expect(lastCallArg).not.toHaveProperty("frequencyComparison");
    expect(lastCallArg).not.toHaveProperty("coOccurrence");
    expect(lastCallArg).not.toHaveProperty("treatmentImpact");
  });

  it("accepts a valid echoed pattern that matches a supplied one exactly", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire3@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = {
      narrative: "n",
      discussionTopics: ["Q?"],
      patterns: [KNOWN_PATTERN],
    };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
  });

  it("rejects an echoed pattern whose id was never supplied", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire4@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = {
      narrative: "n",
      discussionTopics: ["Q?"],
      patterns: [{ ...KNOWN_PATTERN, id: "frequency_increased:BRAIN_FOG" }],
    };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBeGreaterThanOrEqual(500);
  });

  it("rejects a duplicate echoed pattern id", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire5@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = {
      narrative: "n",
      discussionTopics: ["Q?"],
      patterns: [KNOWN_PATTERN, KNOWN_PATTERN],
    };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBeGreaterThanOrEqual(500);
  });

  it("rejects an echoed pattern whose type was changed while keeping the same id", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire6@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = {
      narrative: "n",
      discussionTopics: ["Q?"],
      patterns: [{ ...KNOWN_PATTERN, type: "frequency_decreased" }],
    };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBeGreaterThanOrEqual(500);
  });

  it("rejects an echoed pattern whose evidenceRef was changed while keeping the same id", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire7@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = {
      narrative: "n",
      discussionTopics: ["Q?"],
      patterns: [{ ...KNOWN_PATTERN, evidenceRef: { category: "FATIGUE" } }],
    };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBeGreaterThanOrEqual(500);
  });

  it("accepts a response that echoes back none of the supplied patterns — a subset (including empty) is a valid, intentional response, not a contract violation", async () => {
    // Per brief.ai.ts's own system prompt (rules 6-7): the model only
    // includes a pattern it actually referenced in the narrative or
    // discussion topics, and returns an empty array if none are
    // relevant. A supplied-but-unechoed pattern is not an error —
    // validateStage4Patterns's own doc comment explains why this
    // deliberately does not require the returned set to equal the
    // supplied set.
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4wire8@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"], patterns: [] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(res.status).toBe(201);
  });

  it("persists the canonical Stage 4 interpretation, with deterministic ids and evidenceRef retained exactly, readable via GET", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4persist1@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"], patterns: [] };

    const generateRes = await agent.post("/briefs").send(RANGE);
    expect(generateRes.status).toBe(201);

    // 1, 2, 3: the persisted interpretation (in the POST response,
    // read directly from the created record) retains the deterministic
    // id and the exact evidenceRef — not just some pattern with the
    // right narrative text.
    expect(generateRes.body.data.interpretation).toEqual({
      interpretationVersion: "1.0",
      patterns: [KNOWN_PATTERN],
    });

    // 7. Retrieval returns the same stored interpretation — read back
    // from the persisted record, not the in-memory generate() result.
    const getRes = await agent.get(`/briefs/${generateRes.body.data.id}`);
    expect(getRes.status).toBe(200);
    expect(getRes.body.data.interpretation).toEqual(generateRes.body.data.interpretation);
  });

  it("the persisted, UI-facing interpretation may contain a treatment name, even though the AI never received it", async () => {
    // 4, 5: proves both halves of the privacy boundary in one place —
    // the canonical persisted copy is allowed to contain the name
    // (this is the DTO real UI/PDF code reads), while
    // stage4-ai-projection.test.ts and this file's own CRITICAL test
    // separately prove the AI-facing copy never does.
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4persist2@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: null,
    });
    addSymptomLog(userId, { category: "HOT_FLASH", occurredAt: new Date("2026-01-12") });
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"], patterns: [] };

    const res = await agent.post("/briefs").send(RANGE);

    const treatmentPattern = res.body.data.interpretation.patterns.find(
      (p: { type: string }) => p.type === "treatment_window_changed",
    );
    expect(treatmentPattern).toBeDefined();
    expect(treatmentPattern.observation).toContain("Estradiol patch");

    // The AI-facing payload for this same request still never saw it —
    // same assertion style as the CRITICAL test above, checked again
    // here specifically alongside the persisted-with-name proof, so
    // the contrast is visible in one test rather than two files a
    // reader has to cross-reference.
    const lastCallArg = vi.mocked(briefAi.generate).mock.calls.at(-1)![0];
    expect(JSON.stringify(lastCallArg)).not.toContain("Estradiol");
  });

  it("does not recompute Stage 4 during persistence — the object built once is the exact object persisted", async () => {
    // 8. Structural proof, not an inference from matching output: spy
    // on the real buildStage4Interpretation implementation and count
    // calls for a single generate() request.
    const buildStage4Module = await import("../src/modules/briefs/stage4-interpretation.js");
    const buildSpy = vi.spyOn(buildStage4Module, "buildStage4Interpretation");

    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "stage4persist3@embr.health");
    setUpOneKnownPattern(userId);
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"], patterns: [] };

    const res = await agent.post("/briefs").send(RANGE);

    expect(buildSpy).toHaveBeenCalledTimes(1);
    expect(res.body.data.interpretation.patterns).toEqual(buildSpy.mock.results[0]!.value.patterns);

    buildSpy.mockRestore();
  });
});

describe("GET /briefs/:id — treatment snapshot invariant", () => {
  it("does not query Treatment records at all on read — a previously generated BRIEF cannot change if treatments are later edited or deleted", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-invariant@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: null,
    });
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"] };

    const generateRes = await agent.post("/briefs").send(RANGE);
    const briefId = generateRes.body.data.id as string;

    // Edit and then delete the underlying Treatment record entirely.
    state.treatments[0]!.name = "Changed after generation";
    state.treatments = [];

    const findManyCallsBeforeGet = vi.mocked(prisma.treatment.findMany).mock.calls.length;
    const getRes = await agent.get(`/briefs/${briefId}`);
    expect(getRes.status).toBe(200);

    // The structural proof, not just an outcome that happens to look
    // right: get() must not call prisma.treatment.findMany at all.
    expect(vi.mocked(prisma.treatment.findMany).mock.calls.length).toBe(findManyCallsBeforeGet);

    // The frozen snapshot from generation time — "Estradiol patch",
    // never "Changed after generation" — proving get() reads the
    // persisted treatmentSummary rather than re-deriving it live,
    // exactly as the structural proof above already showed.
    expect(getRes.body.data.treatmentSummary).toEqual([
      { name: "Estradiol patch", category: "HRT", startDate: "2026-01-10", endDate: null },
    ]);
  });
});

describe("Treatment history persistence — generate, re-read, and PDF all agree", () => {
  it("POST /briefs generates treatmentSummary, GET /briefs/:id returns the same values, and the PDF is built from that same persisted brief", async () => {
    const app = createApp();
    const agent = request.agent(app);
    const userId = await registerAndLogin(agent, "tx-persistence@embr.health");
    addTreatment(userId, {
      name: "Estradiol patch",
      category: "HRT",
      startDate: new Date("2026-01-10"),
      endDate: new Date("2026-01-20"),
    });
    aiState.nextResponse = { narrative: "n", discussionTopics: ["Q?"] };

    // 1. POST /briefs generates treatmentSummary.
    const generateRes = await agent.post("/briefs").send(RANGE);
    expect(generateRes.status).toBe(201);
    const expectedTreatmentSummary = [
      { name: "Estradiol patch", category: "HRT", startDate: "2026-01-10", endDate: "2026-01-20" },
    ];
    expect(generateRes.body.data.treatmentSummary).toEqual(expectedTreatmentSummary);
    // No symptom logs added anywhere in this test, in either period —
    // frequencyComparison is [] (computed, found nothing), not null
    // (never computed). Piggybacking this assertion on the existing
    // treatment-persistence test rather than a parallel one, since
    // it's proving the exact same "generate, re-read, PDF all agree"
    // property for a second field.
    expect(generateRes.body.data.frequencyComparison).toEqual([]);
    const expectedTreatmentImpact = {
      name: "Estradiol patch",
      category: "HRT",
      windowDays: 14,
      before: { logCount: 0, days: 14 },
      after: { logCount: 0, days: 10 },
      insufficientData: false,
    };
    expect(generateRes.body.data.treatmentImpact).toHaveLength(1);
    expect(generateRes.body.data.treatmentImpact[0]).toMatchObject(expectedTreatmentImpact);
    const briefId = generateRes.body.data.id as string;

    // 2. GET /briefs/:id returns the same treatmentSummary — read back
    // from the persisted record, not the in-memory generate() result.
    const getRes = await agent.get(`/briefs/${briefId}`);
    expect(getRes.status).toBe(200);
    expect(getRes.body.data.treatmentSummary).toEqual(expectedTreatmentSummary);
    expect(getRes.body.data.frequencyComparison).toEqual([]);
    expect(getRes.body.data.treatmentImpact[0]).toMatchObject(expectedTreatmentImpact);
    expect(getRes.body.data.persistentSymptoms).toEqual([]);
    // The canonical, persisted interpretation is allowed to contain the
    // treatment name — see the dedicated Stage 4 persistence test
    // above for the full proof that the AI-facing copy never does.
    expect(getRes.body.data.interpretation.patterns).toEqual(
      expect.arrayContaining([expect.objectContaining({ type: "treatment_window_changed" })]),
    );

    // 3. GET /briefs/:id/pdf is built from that same persisted brief
    // (via briefService.get(), a separate request from generation) and
    // therefore includes the treatment history — checked structurally
    // by inspecting what buildClinicalBriefPdf was actually called
    // with, the same proof style the snapshot-invariant test above
    // uses, since pdfkit's compressed content streams make grepping
    // raw PDF bytes for treatment text unreliable.
    const pdfRes = await agent.get(`/briefs/${briefId}/pdf`);
    expect(pdfRes.status).toBe(200);
    expect(pdfRes.headers["content-type"]).toContain("application/pdf");

    const pdfCalls = vi.mocked(buildClinicalBriefPdf).mock.calls;
    const lastPdfCallArg = pdfCalls[pdfCalls.length - 1]![0];
    expect(lastPdfCallArg.treatmentSummary).toEqual(expectedTreatmentSummary);
    expect(lastPdfCallArg.frequencyComparison).toEqual([]);
    // No symptom logs added anywhere in this test — no pair to
    // qualify, so null, not an empty object.
    expect(lastPdfCallArg.coOccurrence).toBeNull();
    expect(lastPdfCallArg.treatmentImpact[0]).toMatchObject(expectedTreatmentImpact);
    expect(lastPdfCallArg.persistentSymptoms).toEqual([]);
    expect(lastPdfCallArg.interpretation.patterns).toEqual(
      expect.arrayContaining([expect.objectContaining({ type: "treatment_window_changed" })]),
    );
  });
});

describe("GET/DELETE /briefs — access control", () => {
  async function createBriefFor(agent: ReturnType<typeof request.agent>) {
    aiState.nextResponse = { narrative: "n", discussionTopics: ["t"] };
    const res = await agent.post("/briefs").send(RANGE);
    return res.body.data.id as string;
  }

  it("GET /briefs only lists the current user's briefs", async () => {
    const app = createApp();
    const agentA = request.agent(app);
    await registerAndLogin(agentA, "user-a@embr.health");
    await createBriefFor(agentA);

    const agentB = request.agent(app);
    await registerAndLogin(agentB, "user-b@embr.health");
    await createBriefFor(agentB);

    const res = await agentA.get("/briefs");
    expect(res.status).toBe(200);
    expect(res.body.data.items).toHaveLength(1);
    expect(res.body.data.total).toBe(1);
  });

  it("GET /briefs/:id 404s for another user's brief rather than exposing it", async () => {
    const app = createApp();
    const agentA = request.agent(app);
    await registerAndLogin(agentA, "owner@embr.health");
    const briefId = await createBriefFor(agentA);

    const agentB = request.agent(app);
    await registerAndLogin(agentB, "intruder@embr.health");

    const res = await agentB.get(`/briefs/${briefId}`);
    expect(res.status).toBe(404);
  });

  it("GET /briefs/:id/pdf returns a PDF for the owner", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "pdf-owner@embr.health");
    const briefId = await createBriefFor(agent);

    const res = await agent.get(`/briefs/${briefId}/pdf`);
    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("application/pdf");
  });

  it("DELETE /briefs/:id removes it for the owner", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "deleter@embr.health");
    const briefId = await createBriefFor(agent);

    const del = await agent.delete(`/briefs/${briefId}`);
    expect(del.status).toBe(204);

    const get = await agent.get(`/briefs/${briefId}`);
    expect(get.status).toBe(404);
  });

  it("DELETE /briefs/:id 404s (and does not delete) for another user's brief", async () => {
    const app = createApp();
    const agentA = request.agent(app);
    await registerAndLogin(agentA, "owner2@embr.health");
    const briefId = await createBriefFor(agentA);

    const agentB = request.agent(app);
    await registerAndLogin(agentB, "intruder2@embr.health");

    const del = await agentB.delete(`/briefs/${briefId}`);
    expect(del.status).toBe(404);
    expect(state.briefs.find((b) => b.id === briefId)).toBeDefined();
  });
});
