import { describe, expect, it, vi, beforeEach } from "vitest";
import request from "supertest";
import { randomUUID } from "node:crypto";
import { createApp } from "../src/app.js";
import { buildClinicianSummaryPdf } from "../src/modules/export/pdf.js";

vi.mock("../src/modules/export/pdf.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../src/modules/export/pdf.js")>();
  return {
    ...actual,
    // Wraps (not replaces) the real implementation — PDF bytes are
    // still genuinely generated by pdfkit, matching the existing
    // magic-bytes test below. This only adds the ability to inspect
    // exactly what buildClinicianSummaryPdf was called with, the only
    // reliable way to prove treatments reached the PDF builder:
    // pdfkit's standard fonts compress their content streams by
    // default, so grepping the raw PDF bytes for treatment text isn't
    // a dependable check (same reasoning as brief.test.ts's identical
    // spy for its own PDF route).
    buildClinicianSummaryPdf: vi.fn(actual.buildClinicianSummaryPdf),
  };
});

const { state, nextId } = vi.hoisted(() => {
  return {
    state: {
      users: [] as Array<{
        id: string;
        email: string;
        passwordHash: string;
        role: "MEMBER" | "ADMIN";
        emailVerifiedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
      }>,
      logs: [] as Array<{
        id: string;
        userId: string;
        category: string;
        severity: string;
        occurredAt: Date;
        notes: string | null;
        createdAt: Date;
        updatedAt: Date;
      }>,
      entries: [] as Array<{
        id: string;
        userId: string;
        date: Date;
        flow: string | null;
        isPeriodStart: boolean;
        isPeriodEnd: boolean;
        notes: string | null;
        createdAt: Date;
        updatedAt: Date;
      }>,
      treatments: [] as Array<{
        id: string;
        userId: string;
        name: string;
        category: string;
        startDate: Date;
        endDate: Date | null;
        notes: string | null;
        createdAt: Date;
        updatedAt: Date;
      }>,
    },
    nextId: () => randomUUID(),
  };
});

const now = () => new Date();

vi.mock("../src/lib/redis.js", () => ({
  redis: { ping: vi.fn().mockResolvedValue("PONG"), quit: vi.fn() },
}));

vi.mock("../src/modules/auth/mailer.js", () => ({
  sendVerificationEmail: vi.fn().mockResolvedValue(undefined),
  sendPasswordResetEmail: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("../src/lib/prisma.js", () => ({
  prisma: {
    user: {
      findUnique: vi.fn(({ where }: { where: { email?: string; id?: string } }) => {
        const found = state.users.find((u) => u.email === where.email || u.id === where.id);
        return Promise.resolve(found ?? null);
      }),
      create: vi.fn(({ data }: { data: { email: string; passwordHash: string } }) => {
        const user = {
          id: nextId(),
          email: data.email,
          passwordHash: data.passwordHash,
          role: "MEMBER" as const,
          emailVerifiedAt: null,
          createdAt: now(),
          updatedAt: now(),
        };
        state.users.push(user);
        return Promise.resolve(user);
      }),
      update: vi.fn(({ where, data }: { where: { id: string }; data: Record<string, unknown> }) => {
        const user = state.users.find((u) => u.id === where.id)!;
        Object.assign(user, data);
        return Promise.resolve(user);
      }),
    },
    session: {
      create: vi.fn(({ data }: { data: Record<string, unknown> }) =>
        Promise.resolve({
          id: nextId(),
          revokedAt: null,
          replacedBySessionId: null,
          createdAt: now(),
          ...data,
        }),
      ),
      findUnique: vi.fn().mockResolvedValue(null),
      update: vi.fn(),
      updateMany: vi.fn().mockResolvedValue({ count: 0 }),
      findMany: vi.fn().mockResolvedValue([]),
    },
    emailVerificationToken: {
      updateMany: vi.fn().mockResolvedValue({ count: 0 }),
      create: vi.fn().mockResolvedValue({ id: nextId() }),
      findFirst: vi.fn().mockResolvedValue(null),
      update: vi.fn().mockResolvedValue({}),
    },
    passwordResetToken: {
      updateMany: vi.fn().mockResolvedValue({ count: 0 }),
      create: vi.fn().mockResolvedValue({ id: nextId() }),
      findFirst: vi.fn().mockResolvedValue(null),
      update: vi.fn().mockResolvedValue({}),
    },
    auditLog: {
      create: vi.fn().mockResolvedValue({}),
    },
    onboardingProfile: {
      findUnique: vi.fn().mockResolvedValue(null),
    },
    symptomLog: {
      create: vi.fn(
        ({
          data,
        }: {
          data: Omit<(typeof state.logs)[number], "id" | "createdAt" | "updatedAt">;
        }) => {
          const log = { id: nextId(), createdAt: now(), updatedAt: now(), ...data };
          state.logs.push(log);
          return Promise.resolve(log);
        },
      ),
      findMany: vi.fn(({ where }: { where: { userId: string } }) =>
        Promise.resolve(
          [...state.logs.filter((l) => l.userId === where.userId)].sort(
            (a, b) => a.occurredAt.getTime() - b.occurredAt.getTime(),
          ),
        ),
      ),
    },
    cycleEntry: {
      upsert: vi.fn(
        ({
          where,
          create,
          update,
        }: {
          where: { userId_date: { userId: string; date: Date } };
          create: Omit<(typeof state.entries)[number], "id" | "createdAt" | "updatedAt">;
          update: Partial<(typeof state.entries)[number]>;
        }) => {
          const { userId, date } = where.userId_date;
          const existing = state.entries.find(
            (e) => e.userId === userId && e.date.getTime() === date.getTime(),
          );
          if (existing) {
            Object.assign(existing, update, { updatedAt: now() });
            return Promise.resolve(existing);
          }
          const entry = { id: nextId(), createdAt: now(), updatedAt: now(), ...create };
          state.entries.push(entry);
          return Promise.resolve(entry);
        },
      ),
      findMany: vi.fn(({ where }: { where: { userId: string } }) =>
        Promise.resolve(
          [...state.entries.filter((e) => e.userId === where.userId)].sort(
            (a, b) => a.date.getTime() - b.date.getTime(),
          ),
        ),
      ),
    },
    treatment: {
      create: vi.fn(
        ({
          data,
        }: {
          data: Omit<(typeof state.treatments)[number], "id" | "createdAt" | "updatedAt">;
        }) => {
          const treatment = { id: nextId(), createdAt: now(), updatedAt: now(), ...data };
          state.treatments.push(treatment);
          return Promise.resolve(treatment);
        },
      ),
      // Interprets the same where-clause shape
      // export.repository.ts's listTreatmentsForExport actually
      // builds — startDate <= to (when `to` given) AND (endDate null
      // OR endDate >= from) (when `from` given) — so this mock proves
      // the overlap-semantics query itself, not just that some
      // treatment eventually comes back.
      findMany: vi.fn(
        ({
          where,
        }: {
          where: {
            userId: string;
            startDate?: { lte: Date };
            OR?: Array<{ endDate: null } | { endDate: { gte: Date } }>;
          };
        }) =>
          Promise.resolve(
            [...state.treatments]
              .filter((t) => {
                if (t.userId !== where.userId) return false;
                if (where.startDate && t.startDate.getTime() > where.startDate.lte.getTime()) {
                  return false;
                }
                if (where.OR) {
                  const overlaps = where.OR.some((clause) => {
                    if (clause.endDate === null) return t.endDate === null;
                    return (
                      t.endDate !== null && t.endDate.getTime() >= clause.endDate.gte.getTime()
                    );
                  });
                  if (!overlaps) return false;
                }
                return true;
              })
              .sort((a, b) => a.startDate.getTime() - b.startDate.getTime()),
          ),
      ),
    },
  },
}));

const VALID_PASSWORD = "Sup3rSecret!Pass";

async function registerAndLogin(agent: ReturnType<typeof request.agent>, email: string) {
  await agent.post("/auth/register").send({ email, password: VALID_PASSWORD });
  return agent.post("/auth/login").send({ email, password: VALID_PASSWORD });
}

beforeEach(() => {
  state.users = [];
  state.logs = [];
  state.entries = [];
  state.treatments = [];
  vi.mocked(buildClinicianSummaryPdf).mockClear();
});

describe("GET /export/symptom-logs.csv", () => {
  it("requires authentication", async () => {
    const app = createApp();
    const res = await request(app).get("/export/symptom-logs.csv");
    expect(res.status).toBe(401);
  });

  it("returns a CSV of only the authenticated user's logs", async () => {
    const app = createApp();
    const agentA = request.agent(app);
    const agentB = request.agent(app);
    await registerAndLogin(agentA, "exportA@embr.health");
    await registerAndLogin(agentB, "exportB@embr.health");

    await agentA.post("/symptom-logs").send({
      category: "HOT_FLASH",
      severity: "SEVERE",
      occurredAt: "2026-07-01T00:00:00.000Z",
      notes: "bad one",
    });
    await agentB
      .post("/symptom-logs")
      .send({ category: "BRAIN_FOG", severity: "MILD", occurredAt: "2026-07-02T00:00:00.000Z" });

    const res = await agentA.get("/export/symptom-logs.csv");
    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("text/csv");
    expect(res.headers["content-disposition"]).toContain("embr-symptom-logs.csv");
    expect(res.text).toContain("Hot Flash");
    expect(res.text).toContain("bad one");
    expect(res.text).not.toContain("Brain Fog");
  });
});

describe("GET /export/cycle-entries.csv", () => {
  it("returns a CSV of cycle entries", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "cycleexport@embr.health");
    await agent
      .post("/cycle-entries")
      .send({ date: "2026-07-05", flow: "MEDIUM", isPeriodStart: true });

    const res = await agent.get("/export/cycle-entries.csv");
    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("text/csv");
    expect(res.text).toContain("2026-07-05");
    expect(res.text).toContain("Medium");
  });
});

describe("GET /export/treatments.csv", () => {
  it("requires authentication", async () => {
    const app = createApp();
    const res = await request(app).get("/export/treatments.csv");
    expect(res.status).toBe(401);
  });

  it("returns a CSV of only the authenticated user's treatments, including name, category, dates, and notes", async () => {
    const app = createApp();
    const agentA = request.agent(app);
    const agentB = request.agent(app);
    await registerAndLogin(agentA, "treatmentExportA@embr.health");
    await registerAndLogin(agentB, "treatmentExportB@embr.health");

    await agentA.post("/treatments").send({
      name: "Estradiol patch",
      category: "HRT",
      startDate: "2026-06-01",
      endDate: "2026-06-20",
      notes: "twice weekly",
    });
    await agentB.post("/treatments").send({
      name: "Magnesium",
      category: "SUPPLEMENT",
      startDate: "2026-06-05",
    });

    const res = await agentA.get("/export/treatments.csv");
    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("text/csv");
    expect(res.headers["content-disposition"]).toContain("embr-treatments.csv");
    expect(res.text).toContain("Estradiol patch");
    // The real HRT-acronym fix, not the generic title-case transform
    // (which would otherwise render "Hrt").
    expect(res.text).toContain("HRT");
    expect(res.text).toContain("2026-06-01");
    expect(res.text).toContain("2026-06-20");
    expect(res.text).toContain("twice weekly");
    expect(res.text).not.toContain("Magnesium");
  });

  it("includes an ongoing treatment (no endDate) that started before `from` but is still active inside the requested range", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "treatmentExportOverlap1@embr.health");

    // Started well before the export window and never ended.
    await agent
      .post("/treatments")
      .send({ name: "Ongoing HRT", category: "HRT", startDate: "2026-01-01" });

    const res = await agent.get("/export/treatments.csv").query({
      from: "2026-06-01T00:00:00.000Z",
      to: "2026-06-30T00:00:00.000Z",
    });

    expect(res.status).toBe(200);
    expect(res.text).toContain("Ongoing HRT");
  });

  it("includes a treatment that ended inside the range even though it started before `from`, and excludes one entirely outside the range", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "treatmentExportOverlap2@embr.health");

    await agent.post("/treatments").send({
      name: "Overlapping treatment",
      category: "SUPPLEMENT",
      startDate: "2026-05-15",
      endDate: "2026-06-10",
    });
    await agent.post("/treatments").send({
      name: "Long past treatment",
      category: "MEDICATION",
      startDate: "2025-01-01",
      endDate: "2025-02-01",
    });

    const res = await agent.get("/export/treatments.csv").query({
      from: "2026-06-01T00:00:00.000Z",
      to: "2026-06-30T00:00:00.000Z",
    });

    expect(res.status).toBe(200);
    expect(res.text).toContain("Overlapping treatment");
    expect(res.text).not.toContain("Long past treatment");
  });
});

describe("GET /export/summary.pdf", () => {
  it("returns a PDF document", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "pdfexport@embr.health");
    await agent
      .post("/symptom-logs")
      .send({ category: "JOINT_PAIN", severity: "MODERATE", occurredAt: new Date().toISOString() });

    const res = await agent
      .get("/export/summary.pdf")
      .buffer(true)
      .parse((res, cb) => {
        const chunks: Buffer[] = [];
        res.on("data", (chunk: Buffer) => chunks.push(chunk));
        res.on("end", () => cb(null, Buffer.concat(chunks)));
      });

    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("application/pdf");
    expect(res.headers["content-disposition"]).toContain("embr-health-summary.pdf");
    // PDF files start with the "%PDF-" magic bytes.
    expect((res.body as Buffer).subarray(0, 5).toString("ascii")).toBe("%PDF-");
  });

  it("requires authentication", async () => {
    const app = createApp();
    const res = await request(app).get("/export/summary.pdf");
    expect(res.status).toBe(401);
  });

  it("passes the requesting user's treatments through to the PDF builder", async () => {
    const app = createApp();
    const agent = request.agent(app);
    await registerAndLogin(agent, "pdftreatments@embr.health");
    await agent.post("/treatments").send({
      name: "Estradiol patch",
      category: "HRT",
      startDate: "2026-06-01",
      endDate: "2026-06-20",
      notes: "twice weekly",
    });

    const res = await agent.get("/export/summary.pdf");
    expect(res.status).toBe(200);

    const calls = vi.mocked(buildClinicianSummaryPdf).mock.calls;
    const lastCallArg = calls[calls.length - 1]![0];
    expect(lastCallArg.treatments).toHaveLength(1);
    expect(lastCallArg.treatments[0]).toMatchObject({
      name: "Estradiol patch",
      category: "HRT",
      notes: "twice weekly",
    });
  });
});
